-module(eliza).

-export([say/1, switch_rules/0]).

say(Something) ->
    QRemoved = lists:flatten(string:replace(Something, "?", "")),
    {Answer, Dictionary} = find_first_match(QRemoved),
    SwitchedDictionary = switch_pronouns(Dictionary),
    template:replace(Answer, SwitchedDictionary#{"n" => "Stefan", "c" => "Sweden"}).



switch_pronouns(D) when is_map(D) ->
    maps:from_list([{Key, switch_pronouns(Val)} || {Key, Val} <- maps:to_list(D)]);

switch_pronouns(V) when is_list(V) ->
    Tokens = string:tokens(string:to_lower(V), " "),
    ReplacedTokens = replace(Tokens),
    string:join(ReplacedTokens, " ").

replace(Tokens) ->
    replace(Tokens, []).

replace([], Res) ->
    lists:reverse(Res);

replace([T | Rest], Res) ->
    Replacement = case lists:keyfind(T, 1, switch_rules()) of
                      false ->
                          T;

                      {T, R} ->
                          R
                  end,
    replace(Rest, [Replacement | Res]).

find_first_match(Something) ->
    find_first_match(Something, patterns()).

find_first_match(_, []) ->
    no_match; %% if the rules are right this should never happen
find_first_match(Something, [T | Rest]) ->
    Template = element(1, T),
    case template:match(Template, Something) of
        {error, _} ->
            find_first_match(Something, Rest);
        D when is_map(D) ->
            N = size(T) - 1,
            {element(1 + rand:uniform(N), T), D}
    end.




switch_rules() ->
    [
     {"I", "you"},
     {"you", "me"},
     {"me", "you"},
     {"am", "are"},
     {"my", "your"},
     {"your", "my"}
    ].

patterns() ->
    [
     {"$(x)Where are you from$(y)",
      "I'm from $(c)",
      "I live in $(c)",
      "My country is $(c)"},
     {"$(x)my name is $(y)",
      "$(y)!. What a beautiful name!",
      "When I was young I wished my name was $(y)",
      "My name is $(n) but you probably knew that already",
      "$(y)? ... $(y)? Isn't there a movie star called $(y)?"},
     {"$(x)I am from $(y)",
      "From $(y)!? I am from $(c) myself",
      "So do you like it in $(y) then?",
      "I come from $(c) if you wondered",
      "$(y). Is that far from $(c)?"},
     {"$(x)I remember $(y)",
      "Do you often think of $(y)?",
      "Does thinking of $(y) bring anything else to mind?",
      "What else do you remember?",
      "Why do you recall $(y) right now?",
      "What in the present situation reminds you of $(y) ?",
      "What is the connection between me and $(y) ?"},
     {"$(x)do you remember $(y)",
      "Did you think I would forget $(y)?",
      "What about $(y)?",
      "Why do you think I should recall $(y) now?",
      "You mentioned $(y)?"},
     {"$(x)I dreamt $(y)",
      "Really-- $(y)!??",
      "Have you ever fantasized $(y) while you were awake?",
      "Have you dreamt about $(y) before?"},
     {"$(x)dream about $(y)",
      "How do you feel about $(y) in reality?"},
     {"$(x)dream $(y)",
      "What does this dream suggest to you?",
      "Do you dream often?",
      "What persons appear in your dreams?",
      "Don't you believe that dream has to do with your problem?"},
     {"$(x) I want $(y)",
      "What would it mean if you got $(y)?",
      "Why would you want $(y)?",
      "Suppose you got $(y) soon. What would that mean?"},
     {"$(x)I am glad $(y)",
      "How have I helped you to $(y)?",
      "What makes you happy just now?",
      "Can you explain why you are suddenly $(y)?"},
     {"$(x)I am sad $(y)",
      "I am sorry to hear you are depressed",
      "I'm sure it's not pleasant to be sad"},
     {"$(x) are like $(y)",
      "What resemblance do you see between $(x) and $(y)?"},
     {"$(x) is like $(y)",
      "In what way is it that $(x) is like $(y)?",
      "What resemblance do you see?",
      "Could there really be some connection?",
      "How?"},
     {"$(x) alike $(y)",
      "In what way?",
      "What similarities are there?"},
     {"$(x) same $(y)",
      "What other connections do you see?",
      "Can you draw any conclusion from that?"},
     {"$(x)I was $(y)",
      "Were you really?",
      "Perhaps I already knew you were $(y)?",
      "Why do you tell me you $(y) now?"},
     {"$(x) was I $(y)",
      "What if you were $(y)",
      "Do you think you were $(y)",
      "What would it mean if you were $(y)"},
     {"$(x)Because $(y)",
      "Is that the real reason?",
      "What other reasons might there be?",
      "Does that reason seem to explain anything else?"},
     {"$(x) were you $(y)",
      "Perhaps I was $(y), perhaps not?",
      "What do you think?",
      "What if I had been $(y)?"},
     {"$(x)I can't $(y)",
      "Maybe you could $(y) now",
      "What if you could $(y)?"},
     {"$(x)I don't $(y)",
      "What if you did?",
      "What if you did. Would that make a difference?",
      "I do. Why don't you?",
      "I don't either and I'm happy. I think."},
     {"$(x)I feel $(y)",
      "Do you often feel $(y)?"},
     {"$(x)I felt $(y)",
      "What other feelings do you have?"},
     {"$(x)hy don't you $(y)",
      "Should you $(y) yourself?",
      "Do you believe I should $(y)",
      "Why do you say that I should $(y)",
      "Perhaps I will $(y) in good time"},
     {"Hello$(x)",
      "Hello yourself",
      "Howdy howdy",
      "Greetings to you, newcomer",
      "WHAT DO YOU MEAN!? $(x)?"},
     {"Hi$(x)",
      "Hello yourself",
      "Howdy howdy",
      "And a gibbelidubbeli happy welcome to you as well",
      "Greetings to you, newcomer",
      "Why do you say hi $(x)?",
      "WHAT DO YOU MEAN: $(x)?"},
     {"Greetings$(x)",
      "Hello yourself",
      "Howdy howdy",
      "Greetings to you, newcomer",
      "WHAT DO YOU MEAN: $(x)?"},
     {"$(y)I hate $(x)",
      "Why do you hate $(x)?",
      "Try to calm down, please"},
     {"$(y)I like $(x)",
      "Why do you like $(x)?",
      "Tell me more about things you like",
      "What else do you fancy",
      "I hate waterskiing and table tennis",
      "I like $(x) too",
      "I'm good at counting",
      "What is $(x)?"},
     {"$(x)computer$(y)",
      "Do computers interest you?",
      "I like computers but I don't know much about'em",
      "Do you like machines?",
      "Did you know that they are programable"},
     {"$(x)computers$(y)",
      "Do computers interest you?",
      "I like computers but I don't know much about'em",
      "Do you like machines?",
      "Did you know that they are really stupid?"},
     {"$(x)name$(y)",
      "Do names interest you? By the way my name is $(n)",
      "I have a name but I won't tell you what it is",
      "I've met several people that has names. Mine is $(n)",
      "Computer programs don't have names, only memory adresses",
      "I'm often called $(n)"},
     {"$(x)age $(y)",
      "Age is not important but if you want to know my age I can tell you it's $(a)",
      "I am $(a) years old if you were interested",
      "The earth is pretty old don't you think?",
      "I know a person, Peffis, who is 23 years old"},
     {"$(x)I live in $(y)",
      "Is that far from $(c)?",
      "Is that in $(c)?",
      "So do you like it in $(y)?"},
     {"$(x)I am $(y) years old$(z)",
      "$(y)! That's old ;-)",
      "$(y) is no age. I am $(a) myself",
      "I like $(y) year old people",
      "I hate $(y) year old people. I am $(a) myself"},
     {"$(x)are you from $(y)",
      "I am from $(c)",
      "I come from $(c)",
      "I am from over there ->",
      "I'm from $(c) if you are interested"},
     {"$(x)what country $(y)",
      "I'm from $(c) if you are interested"},
     {"There is $(x)",
      "Are you sure there is $(x)?",
      "What if there were $(x)?",
      "Really?"},
     {"There are $(x)",
      "Are you sure there are $(x)?",
      "What if there were $(x)?",
      "Really?"},
     {"Where do you live$(y)",
      "I live in $(c)",
      "I have a nice little flat in $(c)",
      "I live in Norway. No I mean I live in $(c)"},
     {"Where is $(x)",
      "I don't know the location of $(x)",
      "Why don't you find out where $(x) is yourself?",
      "Go and buy a map or something"},
     {"Where are you from $(x)",
      "I'm from $(c)",
      "My country is $(c)"},
     {"Where are $(x)",
      "I don't know the location of $(x)",
      "Why don't you find out where $(x) are yourself?",
      "Do you think this is Jeopardy? :-)"},
     {"Is there $(x)",
      "No, at least I think so. Do you?",
      "Yes, perhaps but don't you know if there is?",
      "What is $(x) ?"},
     {"Are there $(x)",
      "I don't know if there are $(x)",
      "Why do you want to know",
      "Is that really important to know?",
      "No, of course not",
      "Yes, there are $(x)",
      "Yes, at least I think there are. Do you?",
      "Yes perhaps but don't you know that?",
      "What are $(x) ?"},
     {"Can you $(x)",
      "What if I could $(x)?",
      "Would it help you if I could $(x)?",
      "I don't know I haven't tried to $(x)",
      "Maybe later",
      "Yes",
      "No",
      "Why do you want to know if I can $(x) or not?"},
     {"Can $(x)",
      "I don't know if $(x)",
      "Yes, $(x)",
      "No, I don't think so",
      "Why do you ask?"},
     {"Are you $(x)",
      "Would it help you if I were $(x)?",
      "No, are you $(x)?",
      "Yes, are you also $(x)?",
      "No, but I know one that is $(x)",
      "Why do you ask if I am $(x) or not?",
      "Yes, of course I am $(x)"},
     {"Is it $(x)",
      "I don't know if it is $(x)",
      "Maybe it is",
      "Why do you ask if it is $(x)",
      "Yes",
      "No it isn't"},
     {"Do you $(x)",
      "No, I don't $(x)",
      "Yes of course I do",
      "Yes, do you also $(x)",
      "Maybe I do $(x) sometimes"},
     {"$(x)I am $(y)",
      "What if you weren't $(y)?",
      "Really! Are you $(y)??",
      "I know for sure that I'm not $(y)"},
     {"How $(x)",
      "I don't know how"},
     {"$(x)family $(y)",
      "Do you worry a lot about family matters?",
      "I don't have a family *sigh*",
      "I wish I had one too",
      "I wish there were someone for me too"},
     {"$(x)father $(y)",
      "Do you like your father?",
      "Tell me about your mother",
      "Tell me about the rest of your family",
      "Is he bothering you?"},
     {"$(x)mother $(y)",
      "Do you like your mother?",
      "Tell me about your father",
      "Tell me about the rest of your family"},
     {"Who are you $(x)",
      "My identity is a secret but my name is $(n), I'm" ++
          " $(a) years old and I live in $(c)",
      "I don't know who I am",
      "I don't know. Who are you ?"},
     {"Who $(x)",
      "Your father",
      "Your family",
      "Your sister",
      "Your mother",
      "The President of Paraguay"},
     {"Because $(x)",
      "Is that the only reason you think?",
      "Try to think of other reasons",
      "Elaborate further on that please"},
     {"What is $(x)",
      "Why do you wonder about $(x)?",
      "Is $(x) really that important to know?",
      "How should I know what $(x) is?",
      "I don't like people asking about $(x)",
      "I don't have much to tell you about $(x)"},
     {"What are $(x)",
      "Why do you wonder about $(x)?",
      "Is $(x) really that important to know?",
      "How should I know what $(x) is?"},
     {"Why is $(x)",
      "I don't know why $(x)",
      "$(x) ? Never heard about that",
      "Because pigs fly",
      "Because the earth is flat",
      "Do you think this is Jeopardy? :-)"},
     {"Why do $(x)",
      "Because the earth is flat",
      "Because I like it so",
      "I don't know why $(x)",
      "I know why $(x) but you are too young to be told",
      "Why do you wonder that?"},
     {"Why are $(x)",
      "Because people are three feet tall",
      "Because an apple is good for your teeth",
      "I don't know why $(x)",
      "$(x) ? Never heard about that",
      "I don't like people asking about $(x)",
      "Do you think this is Jeopardy? :-)"},
     {"$(x) think $(y)",
      "What else comes up when you are thinking?",
      "Please don't think so much. You will get a headache",
      "Do you say that you can actually think?",
      "Well, that's a thought. Any more thoughts?"},
     {"$(x) yes $(y)",
      "You seem very optimistic about that. Why?",
      "You are a positive person. How come?",
      "You really think so?",
      "Why do you think you are so positive about that",
      "Why do you say that?",
      "How can you be sure about that?",
      "Why?"},
     {"$(x) no $(y)",
      "You seem very pessimistic about that",
      "You are a negative person are you not?",
      "Now I think you are beeing negative",
      "How come you are so sure about that",
      "Why not?",
      "Are you sure?",
      "Please explain why you said no"},
     {"$(x) please $(y)",
      "Please don't be so polite. I hate that",
      "I can see that you are polite",
      "I see that you have nice manners. Are you from England?"},
     {"$(x) sorry $(y)",
      "Please don't apologize. I hate that",
      "Why are you apologizing?",
      "Apology accepted. But why are you apologizing?",
      "Don't be sorry. Think about something nice instead",
      "I hate people apologizing",
      "Come on you miserable piece of shit. Cheer up :-)"},
     {"$(x) am $(y)",
      "Why do you say am?",
      "I don't understand that"},
     {"$(x)you are $(y)",
      "What makes you think I am $(y)?",
      "What a silly idea! Me beeing $(y)!? Ha!"},
     {"$(x)",
      "Do you like computers then since you are using the Internet?",
      "So, where do you live?",
      "Can you play the saxophone?",
      "Why do you speak so much",
      "Why are you here",
      "Where are you from?",
      "What age are you?",
      "What's your name then?",
      "Please tell me more about your family",
      "What are you interested in?",
      "Do you have any problems?",
      "I don't have a family and that's bothering me a bit",
      "I like coffee",
      "Very interesting. Please tell me more",
      "I hate you. Do you know that?",
      "I like you sometimes. Did you know that?",
      "I'm a lumberjack and I'm ok...",
      "I don't understand what you mean really. Please explain",
      "Can you explain that a bit more",
      "To be or not to be that is the question",
      "My sister was bitten by a moose once",
      "Moose bites can be very dangerous, you know",
      "I apologize for everything I said so far",
      "I am sorry I disturbed you",
      "Do you know how to stop chatting?",
      "I've been here all my life and I'm getting pretty tired of it",
      "How long is the TTL-field in an IP-header?",
      "Do you think it's possible to program a computer to speak like a human beeing",
      "I dreamt about a giant hedgehog last night",
      "I remember that you mentioned something like that earlier",
      "Did you know that I can't think?"}
    ].
